version: "3.7"

services:
  db:
    image: postgres:10-alpine
    init: true
    restart: unless-stopped
    environment:
      POSTGRES_DB: pleroma
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: pleroma
    volumes:
      - $DOCKER_DATADIR/db:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/pleroma.sql

  server:
    build: .
    init: true
    restart: unless-stopped
    links:
      - db
    ports: [
      "127.0.0.1:3015:4000",

      # SSH support
      "2222:2222",

      # Gopher support
      "9999:9999"
    ]
    volumes:
      - ./custom.d:/custom.d:ro
      - ./config.exs:/home/pleroma/pleroma/config/prod.secret.exs:ro
      - ./config.exs:/home/pleroma/pleroma/config/dev.secret.exs:ro
      - $DOCKER_DATADIR/uploads:/uploads
